server:
  port: 9527

spring:
  application:
    name: service-zuul-gateway

# 该段配置可以查看ZuulProperties类
zuul:
  # url统一添加前缀
  prefix: /springcloud
  # 忽略掉微服务名，采用别名访问
  # 如果想忽略掉所有 ignoredServices: "*"
  ignoredServices: userinfo-service
  routes:
    # 服务名称
    userservice.serviceid: userinfo-service
    # 服务别名
    userservice.path: /userapp/**
    
eureka:
#  instance:
#    instance-id: service-zuul-gateway   #服务名#
#    prefer-ip-address: true  # 访问路径可以显示ip
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7013.com:7013/eureka/
      
# 配置点击某个服务后跳转到相应的监控信息info页面，http://192.168.190.1:8080/actuator/info      
info:
  app.name: service-zuul-gateway
  build.artifactId: $project.artifactId$      
  build.version: $project.version$
  
 