server:
  port: 8022

spring:
  application:
    name: UserInfo-Service-Consumer-Ribbon
    
eureka:
  instance:
    hostname: localhost
    instance-id: UserInfo-Service-Consumer-Ribbon   #服务名#
    prefer-ip-address: true  # 访问路径可以显示ip
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7013.com:7013/eureka/