server:
  port: 9060

spring:
  application:
    name: service-zuul-gateway


## 方式二
#zuul:
#  routes:
#    userservice:   ## 只是给路由起个名字
#      path: /user/**
#      serviceId: UserInfo-Service

## 方式三
#zuul:
#  routes:
#    userservice:
#      path: /user/**
#      url: http:localhost:

zuul:
  prefix: /userconsumer
  ignoredServices: Service-Consumer-Feign
  routes:
    userservice:
      serviceid: UserInfo-Service
      path: /userzuul/**


eureka:
#  instance:
#    instance-id: service-zuul-gateway   #服务名#
#    prefer-ip-address: true  # 访问路径可以显示ip
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
      
project:
  artifactId: service-zuul-gateway
  version: 1.0.1
# 配置点击某个服务后跳转到相应的监控信息info页面，http://192.168.190.1:8080/actuator/info
info:
  app.name: service-zuul-gateway
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
  
 